package javafxapplication2;

public class Input
{

    // 1: random array generated automatically
    public static void createInput(int numberOfElements, int maxNumberReached)
    {
        Main.arrayInput= new int[numberOfElements];
        try
        {
            Main.arrayInput=ArrayGen.createRandomArray(numberOfElements, maxNumberReached);
        }
        catch(Exception ex)
        {
            System.out.println("Eccezzione Generata --> " + ex.getLocalizedMessage());
        }
    }

    // 2: array generated by user input
    public static void createInput(int[] a)
    {
        Main.arrayInput= new int[a.length];
        for(int i=0; i<a.length; i++)
        {
            Main.arrayInput[i]=a[i];
        }
    }


    Input()
    {
        Main.arrayInput=new int[Main.ARRAY_LENGHT];
    }

}

